server:
  port: 80

spring:
  cloud:
    gateway:
      routes:
        - id: v1-api-path
          uri: http://localhost:8081
          predicates:
            - Path=/v1/**
          filters:
            - RewritePath=/v1/(?<path>.*), /$\{path}
        - id: v2-api-path
          uri: http://localhost:8083
          predicates:
            - Path=/v2/**
          filters:
            - RewritePath=/v2/(?<path>.*), /$\{path}

        - id: v1-api-param
          uri: http://localhost:8081
          predicates:
            - Query=version,v1
        - id: v1-api-param
          uri: http://localhost:8083
          predicates:
            - Query=version,v2

        - id: v1-api-header
          uri: http://localhost:8081
          predicates:
            - Header=X-API-VERSION,v1
        - id: v1-api-header
          uri: http://localhost:8081
          predicates:
            - Header=X-API-VERSION,v2

        - id: v1-api-accept
          uri: http://localhost:8081
          predicates:
            - Header=Accept, application/vnd.benggrae.com.v1\+json
        - id: v2-api-accept
          uri: http://localhost:8081
          predicates:
            - Header=Accept, application/vnd.benggrae.com.v1\+json
logging:
  level:
    root: debug
